server:
  # 8003表示注册到zookeeper服务器的支付服务提供者端口号
  port: 8003
spring:
  application:
    # 服务别名---注册zookeeper到注册中心的名称
    name: cloud-provider-payment
  cloud:
    zookeeper:
      # zookeeper服务器 IP
      connect-string: localhost:2181